name: Deploy to Chrome Web Store

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build extension
        run: npm run build

      - name: Zip extension
        run: zip -r extension.zip ./path/to/your/extension/files

      # - name: Upload to Chrome Web Store
      #   uses: lolopinto/chrome-webstore-upload@v1.0.5
      #   with:
      #     client_id: ${{ secrets.CHROME_WEB_STORE_CLIENT_ID }}
      #     client_secret: ${{ secrets.CHROME_WEB_STORE_CLIENT_SECRET }}
      #     refresh_token: ${{ secrets.CHROME_WEB_STORE_REFRESH_TOKEN }}
      #     extension_id: your_chrome_extension_id
      #     zip_file: extension.zip
