name: Deploy to Chrome Web Store

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build extension
        run: npm run build

      - name: Upload to Chrome Web Store
        uses: google-chrome/publish@v1
        with:
          client_id: ${{ secrets.CHROME_WEB_STORE_CLIENT_ID }}
          client_secret: ${{ secrets.CHROME_WEB_STORE_CLIENT_SECRET }}
          refresh_token: ${{ secrets.CHROME_WEB_STORE_REFRESH_TOKEN }}
          app_id: your_chrome_extension_app_id
          zip: path/to/your/extension.zip
